### PR TITLE
correct mispellings

### PR DESCRIPTION
**Pull request by sgsfak**

### CODE REVIEW

**Comment by apterf** [comment]
Hey sgsfak,

We are also currently in the process of trying to use this library. Have you had any success with it? We are struggling to generate valid SAML requests.

Thanks,
Apter

**Comment by sgsfak** [comment]
Hi Apter,

I 've managed to implement a Service Provider with this library but made additional changes (incorporate signing, decryption of the SAML response) to work (at least) with our Identity Provider for an internal project. I will probably make additional commits when I clean up the code and test it more. 

Stelios

**Comment by apterf** [comment]
Hi Stelios,

Seems like we are doing some similar things!

We are trying to test this library with Microsoft Azure as a reference. However, it claims that it is not a valid request format.
Looking at the protocol, we find also some problems regarding to the "ID" in the request XML. Not sure whether it helps you or not but you may take a look.

According to [Microsoft Azure Single Sign-On (SAML protocol)](https://msdn.microsoft.com/en-us/library/azure/dn195589.aspx):
- ID. Azure Active Directory uses the value of the ID attribute to populate the InResponseTo attribute of the SAML Response that it returns. The SAML specification requires that the value of ID must not begin with a number. A common strategy to generate a value for the ID attribute is to prepend a predefined string, such as "id", to the string representation of a GUID.

Before Clojure, we used Javascript to implement the SAML login (both Azure and our company partner). 
It [generates a random 20 unit string](https://github.com/AzureAD/passport-azure-ad/blob/6e32e43d2b359e2b5caa62501f3a9232f5fc1f4f/lib/passport-azure-ad/saml.js#L140) then [append to char "id"](https://github.com/AzureAD/passport-azure-ad/blob/6e32e43d2b359e2b5caa62501f3a9232f5fc1f4f/lib/passport-azure-ad/saml.js#L140).

We will also work on this and update you if we have other findings.

Apter =P

**Comment by sgsfak** [comment]
Hi , thanks for the info. In my version i am putting an "_" (underscore) in the auto increment "saml-id" of the lib. Our identity provider also required the presence of the "Destination" tag in the AuthnRequest, which does not seem to be the case of Azure. (Ah, the joy of the interoperable implementations of standards :-) )

thanks, Stelios

**Comment by lvh** [comment]
Also trying to use this library, looking forward to contributing some patches :)

@vlacs: Are you still interested in maintaining this library? Should I be submitting patches here?

**Comment by lvh** [comment]
Oops, looks like I should be pinging @jrdoane not @vlacs :)

**Comment by jrdoane** [comment]
Hi @lvh , I just noticed the updates you made. I'll pull them in. This was, if I recall correctly, my first Clojure project but we never ended up using it so it never got any additional love. If you want to contibute changes, you can but, I don't currently have plans to maintain this project unless the need for it were to arise.

**Comment by ryallk** [comment]
Hey @sgsfak, @lvh any updates on this library? We are interested in using it but still have not managed to generate valid SAML requests.

**Comment by lvh** [comment]
@ryallk I'm not involved in this library; I was just seeing if I could contribute to it.

**Comment by sgsfak** [comment]
I have made some changes for the SP functionality (e.g. added signing of requests and decryption of responses from IdP) using [openSAML](https://wiki.shibboleth.net/confluence/display/OpenSAML/Home) that works for _my_ setting. I will commit a new version in a week or so since I am very busy right now

**Comment by apterf** [comment]
Great to hear O_O+

**Comment by lvh** [comment]
@sgsfak Is that going into saml20-clj, or a separate library? It seems we're not using OpenSAML right now.

**Comment by sjmackenzie** [comment]
Yes, personally I would love to see this code. Do you have an ETA? (@sgsfak)

**Comment by sgsfak** [comment]
Wow, I didn't expect so much interest! :-) 

@lvh Yes saml20-clj did not originally use opensaml, I added it (reluctantly) because it offered an easy way to support the decryption of the responses. For the signing of the SP requests to IdP I introduced another dependency on [Apache Santuario](https://santuario.apache.org) There's an overlap in functionality -- Santuario could also decrypt but I found the OpenSAML API easier. For example the following code is for creating a "decrypter" loading the private key from a keystore:

```
(defn make-xml-decrypter [keystore-filename keystore-password key-alias]
  (org.opensaml.DefaultBootstrap/bootstrap)
  (let [ks (saml-shared/load-key-store keystore-filename keystore-password)
        private-key (.getKey ks key-alias (.toCharArray keystore-password))
        decryption-cred (doto (new org.opensaml.xml.security.x509.BasicX509Credential) 
                          (.setPrivateKey private-key))
        decrypter (new org.opensaml.saml2.encryption.Decrypter
                       nil
                       (new org.opensaml.xml.security.keyinfo.StaticKeyInfoCredentialResolver decryption-cred)
                       (new org.opensaml.xml.encryption.InlineEncryptedKeyResolver))]
    decrypter))
```

@sjmackenzie I need to make a few changes to make it reusable for others since it is now incorporated on a private project of mine. I expect to do it by this weekend.

**Comment by sgsfak** [comment]
So I have a new version committed at https://github.com/sgsfak/saml20-clj 
Sorry for the delay, it took me more than I expected :-)

**Comment by sjmackenzie** [comment]
Hey, neat! Us devs just said "Yay!". You're awesome @sgsfak!

**Comment by sgsfak** [comment]
In order to test the demo SP you need first to create a public/private key pair and store them in a keystore like so:

```
    keytool -genkey -alias my-sp -keyalg RSA -keystore keystore.jks -keysize 2048
```

Then check the [dev/demo_sp.clj](https://github.com/sgsfak/saml20-clj/blob/dev/dev/demo_sp.clj#L60) and change the configuration there for the `:keystore-file`, `:keystore-password`, and `:key-alias`. The default IdP is [openidp.feide.no](https://openidp.feide.no) so you also need to register there or use your own IdP if have any.

When you ve made these changes, you can launch the demo SP:

```
   lein run -m demo-sp/main
```

..and then visit [http://localhost:8080/](http://localhost:8080/)

**Pull request merged**
